{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zetauction.fullname" . }}
  labels:
    {{- include "zetauction.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-connection: {{ .Values.secrets.database.connectionString | quote }}
  redis-connection: {{ .Values.secrets.redis.connectionString | quote }}
  jwt-secret: {{ .Values.secrets.jwt.secretKey | quote }}
{{- end }}
